[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
futures-util = "0.3.31"
log = "0.4.22"
tokio = { version = "1.41.1", features = ["full"] }
tokio-tungstenite = "0.24.0"
warp = "0.3.7"
