# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: counter.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'counter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcounter.proto\x12\x07\x63ounter\"\x07\n\x05\x45mpty\"\'\n\nProtoCount\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x17\n\tProtoPing\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\tProtoText\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xa6\x01\n\x0e\x43ounterService\x12*\n\x04Ping\x12\x12.counter.ProtoPing\x1a\x0e.counter.Empty\x12\x38\n\x11UpdateCounterWith\x12\x13.counter.ProtoCount\x1a\x0e.counter.Empty\x12.\n\x08SendText\x12\x12.counter.ProtoText\x1a\x0e.counter.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'counter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PROTOCOUNT']._serialized_start=35
  _globals['_PROTOCOUNT']._serialized_end=74
  _globals['_PROTOPING']._serialized_start=76
  _globals['_PROTOPING']._serialized_end=99
  _globals['_PROTOTEXT']._serialized_start=101
  _globals['_PROTOTEXT']._serialized_end=138
  _globals['_COUNTERSERVICE']._serialized_start=141
  _globals['_COUNTERSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
