# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import counter_pb2 as counter__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in counter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CounterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/counter.CounterService/Ping',
                request_serializer=counter__pb2.ProtoPing.SerializeToString,
                response_deserializer=counter__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateCounterWith = channel.unary_unary(
                '/counter.CounterService/UpdateCounterWith',
                request_serializer=counter__pb2.ProtoCount.SerializeToString,
                response_deserializer=counter__pb2.Empty.FromString,
                _registered_method=True)
        self.SendText = channel.unary_unary(
                '/counter.CounterService/SendText',
                request_serializer=counter__pb2.ProtoText.SerializeToString,
                response_deserializer=counter__pb2.Empty.FromString,
                _registered_method=True)


class CounterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCounterWith(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CounterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=counter__pb2.ProtoPing.FromString,
                    response_serializer=counter__pb2.Empty.SerializeToString,
            ),
            'UpdateCounterWith': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCounterWith,
                    request_deserializer=counter__pb2.ProtoCount.FromString,
                    response_serializer=counter__pb2.Empty.SerializeToString,
            ),
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=counter__pb2.ProtoText.FromString,
                    response_serializer=counter__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'counter.CounterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('counter.CounterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CounterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/counter.CounterService/Ping',
            counter__pb2.ProtoPing.SerializeToString,
            counter__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCounterWith(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/counter.CounterService/UpdateCounterWith',
            counter__pb2.ProtoCount.SerializeToString,
            counter__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/counter.CounterService/SendText',
            counter__pb2.ProtoText.SerializeToString,
            counter__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
